version: 1.2.0.{build}

skip_non_tags: true

image: Visual Studio 2019
clone_depth: 1

# cache:
#   - clonehero-win64.7z
#   - clonehero-win64
#   - CH-Libraries

install:
  - echo Downloading Clone Hero
  - ps: Start-FileDownload 'http://dl.clonehero.net/clonehero-v.23.2.2/clonehero-win64.7z'
  - echo Unzipping Clone Hero
  - ps: 7z x clonehero-win64.7z
  - echo Moving common folder
  - ps: New-Item -ItemType Directory -Path 'CH-Libraries'
  - ps: Copy-Item -Path '.\clonehero-win64\Clone Hero_Data\Managed\*' -Destination 'CH-Libraries' -Recurse 

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"

platform: Any CPU
configuration: Release

artifacts:
  - path: AccuracyIndicator\bin\Release\AccuracyIndicator.dll
    name: AccuracyIndicator
  - path: ComboIndicator\bin\Release\ComboIndicator.dll
    name: ComboIndicator
  - path: ExtraSongUI\bin\Release\ExtraSongUI.dll
    name: ExtraSongUI
  - path: PerfectMode\bin\Release\PerfectMode.dll
    name: PerfectMode

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Placeholder description: maybe I should add install instructions here?'
    auth_token:
      secure: VZ3WQUK/e5R7Roa5Vl0SRnK1Z1lrkWv861LeOpomdmdhi1x8SQtqpc8Pa5gomgbc
    artifact: AccuracyIndicator,ComboIndicator,ExtraSongUI,PerfectMode
    on:
      branch: master
      APPVEYOR_REPO_TAG: true