version: 1.5.0.{build}

image: Visual Studio 2019
clone_depth: 1

cache:
  - BepInEx-Libraries
  - CH-Libraries

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

install:
  - echo Downloading Clone Hero
  - ps: |
        if (-not (Test-Path .\CH-Libraries)) {
            Start-FileDownload 'http://dl.clonehero.net/clonehero-v.23.2.2/clonehero-win64.7z'
            7z x clonehero-win64.7z
            New-Item -ItemType Directory -Path 'CH-Libraries'
            Copy-Item -Path '.\clonehero-win64\Clone Hero_Data\Managed\*' -Destination 'CH-Libraries' -Recurse
        }
  - echo Downloading BepInEx
  - ps: |
        if (-not (Test-Path .\BepInEx-Libraries)) {
            Start-FileDownload 'https://github.com/BepInEx/BepInEx/releases/download/v5.3/BepInEx_x64_5.3.0.0.zip'
            7z x BepInEx_x64_5.3.0.0.zip
            New-Item -ItemType Directory -Path 'BepInEx-Libraries'
            Copy-Item -Path '.\BepInEx\core\*' -Destination 'BepInEx-Libraries' -Recurse
        }

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"

platform: Any CPU
configuration: 
  - Debug
  - Release


before_package:
  - ps: |
        @("AccuracyIndicator", "BiendeoCHLib", "ComboIndicator", "ExtraSongUI", "LegacyModLoader", "PerfectMode", "SplashTextEditor") | % {
            New-Item -Type Directory -Path ".\Artifacts\$_\BepInEx\plugins\$_"
            New-Item -Type Directory -Path ".\Artifacts\Debug\BepInEx\plugins\$_"
            Copy-Item -Path ".\$_\bin\Release\$_.dll" -Destination ".\Artifacts\$_\BepInEx\plugins\$_"
            Copy-Item -Path ".\$_\bin\Debug\$_.dll" -Destination ".\Artifacts\Debug\BepInEx\plugins\$_"
            7z a .\Artifacts\$_.zip .\Artifacts\$_\BepInEx
        }
        7z a .\Artifacts\Debug.zip .\Artifacts\Debug\BepInEx

artifacts:
  - path: Artifacts\AccuracyIndicator.zip
    name: AccuracyIndicator
  - path: Artifacts\BiendeoCHLib.zip
    name: BiendeoCHLib
  - path: Artifacts\ComboIndicator.zip
    name: ComboIndicator
  - path: Artifacts\Debug.zip
    name: Debug
  - path: Artifacts\ExtraSongUI.zip
    name: ExtraSongUI
  - path: Artifacts\LegacyModLoader.zip
    name: LegacyModLoader
  - path: Artifacts\PerfectMode.zip
    name: PerfectMode
  - path: Artifacts\SplashTextEditor.zip
    name: SplashTextEditor

deploy:
  - provider: GitHub
    release: v$(APPVEYOR_BUILD_VERSION)-pre
    description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
    auth_token:
      secure: VZ3WQUK/e5R7Roa5Vl0SRnK1Z1lrkWv861LeOpomdmdhi1x8SQtqpc8Pa5gomgbc
    artifact: AccuracyIndicator,BiendeoCHLib,ComboIndicator,Debug,ExtraSongUI,LegacyModLoader,PerfectMode,SplashTextEditor
    prerelease: true
    skip_tags: true
    on:
      branch: master
      APPVEYOR_REPO_TAG: false

  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Placeholder description: maybe I should add install instructions here?'
    auth_token:
      secure: VZ3WQUK/e5R7Roa5Vl0SRnK1Z1lrkWv861LeOpomdmdhi1x8SQtqpc8Pa5gomgbc
    artifact: AccuracyIndicator,BiendeoCHLib,ComboIndicator,ExtraSongUI,LegacyModLoader,PerfectMode,SplashTextEditor
    prerelease: false
    on:
      branch: master
      APPVEYOR_REPO_TAG: true