version: 1.5.2.{build}

image: Visual Studio 2019
clone_depth: 1

branches:
  only:
    - master

skip_tags: true

cache:
  - BepInEx-Libraries
  - CH-Libraries

install:
  - echo Downloading Clone Hero
  - ps: |
        if (-not (Test-Path .\CH-Libraries)) {
            Start-FileDownload 'http://dl.clonehero.net/clonehero-v.23.2.2/clonehero-win64.7z'
            7z x clonehero-win64.7z
            New-Item -ItemType Directory -Path 'CH-Libraries'
            Copy-Item -Path '.\clonehero-win64\Clone Hero_Data\Managed\*' -Destination 'CH-Libraries' -Recurse
        }
  - echo Downloading BepInEx
  - ps: |
        if (-not (Test-Path .\BepInEx-Libraries)) {
            Start-FileDownload 'https://github.com/BepInEx/BepInEx/releases/download/v5.4.17/BepInEx_x64_5.4.17.0.zip'
            7z x BepInEx_x64_5.4.11.0.zip
            New-Item -ItemType Directory -Path 'BepInEx-Libraries'
            Copy-Item -Path '.\BepInEx\core\*' -Destination 'BepInEx-Libraries' -Recurse
        }

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"

platform: Any CPU
configuration:
  - Debug
  - Release

before_build:
  - nuget restore

after_build:
  - ps: |
        @("AccuracyIndicator", "BiendeoCHLib", "ComboIndicator", "ExtraSongUI", "LegacyModLoader", "PerfectMode", "SplashTextEditor") | % {
            New-Item -Type Directory -Path ".\Artifacts\$env:CONFIGURATION\$_\BepInEx\plugins\$_"
            Copy-Item -Path ".\$_\bin\$env:CONFIGURATION\$_.dll" -Destination ".\Artifacts\$env:CONFIGURATION\$_\BepInEx\plugins\$_"
            7z a .\Artifacts\$_$(if ($env:CONFIGURATION -eq "Release") { [string]::Empty } else { "-Debug" }).zip .\Artifacts\$env:CONFIGURATION\$_\BepInEx
        }

artifacts:
  - path: Artifacts\AccuracyIndicator.zip
    name: AccuracyIndicator
  - path: Artifacts\AccuracyIndicator-Debug.zip
    name: AccuracyIndicator-Debug
  - path: Artifacts\BiendeoCHLib.zip
    name: BiendeoCHLib
  - path: Artifacts\BiendeoCHLib-Debug.zip
    name: BiendeoCHLib-Debug
  - path: Artifacts\ComboIndicator.zip
    name: ComboIndicator
  - path: Artifacts\ComboIndicator-Debug.zip
    name: ComboIndicator-Debug
  - path: Artifacts\ExtraSongUI.zip
    name: ExtraSongUI
  - path: Artifacts\ExtraSongUI-Debug.zip
    name: ExtraSongUI-Debug
  - path: Artifacts\LegacyModLoader.zip
    name: LegacyModLoader
  - path: Artifacts\LegacyModLoader-Debug.zip
    name: LegacyModLoader-Debug
  - path: Artifacts\PerfectMode.zip
    name: PerfectMode
  - path: Artifacts\PerfectMode-Debug.zip
    name: PerfectMode-Debug
  - path: Artifacts\SplashTextEditor.zip
    name: SplashTextEditor
  - path: Artifacts\SplashTextEditor-Debug.zip
    name: SplashTextEditor-Debug

deploy:
  - provider: GitHub
    release: v$(APPVEYOR_BUILD_VERSION)-pre
    description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
    auth_token:
      secure: VZ3WQUK/e5R7Roa5Vl0SRnK1Z1lrkWv861LeOpomdmdhi1x8SQtqpc8Pa5gomgbc
    artifact: /.*/
    prerelease: true
    skip_tags: true
    on:
      branch: master
      APPVEYOR_REPO_TAG: false